services:
  - docker

script:
  - docker build . -t rampadc/toddler-world-data:latest

before_deploy:
  - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"

deploy:
  provider: script
  script: docker push rampadc/toddler-world-data:latest
  on:
    branch: master